locales:
  en:
    name: Inari Sami Keyboards
    description: >-
      Mobile OS keyboards for the Inari Sami language from the Divvun group at
      UiT.
  nb:
    name: Inari Sami tastatur
    description: Mobiltastatur for Inari Sami fra Divvun-gruppa.
author: 'Giellatekno & Divvun, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
