internalName: smn

locales:
  en:
    name: &bundleName "Inari Sami Keyboards"
    description: "Mobile OS keyboards for the Inari Sami language from the Divvun group at UiT."
  nb:
    name: "Inari Sami tastatur"
    description: "Mobiltastatur for Inari Sami fra Divvun-gruppa."

author: Trond Trosterud, UiT Norgga 치rktala코 universitehta
email: trond.trosterud@uit.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [smn,smn-macos,smn-windows]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.smn
    icon: images/smn-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.smn
    bundleName: *bundleName
    icon: images/smn-icon.png
  osx:
    <<: *AppleID
    icon: images/smn-keyboard-menu-icon.png
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    version: 0.1.0
    resources: doc
