internalName: smn

locales:
  en:
    name: &bundleName "Inari Sami Keyboards"
    description: "Mobile OS keyboards for the Inari Sami language from the Divvun group at UiT."
  nb:
    name: "Inari Sami tastatur"
    description: "Mobiltastatur for Inari Sami fra Divvun-gruppa."

author: Trond Trosterud, UiT Norgga 치rktala코 universitehta
email: trond.trosterud@uit.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

# Alternative list format, easier to read:
layouts:
  - smn
  - smn-macos
  - smn-macos-alt-dh
  - smn-windows
  - smn-windows-alt-dh

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.smn
    icon: images/smn-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.smn
    bundleName: *bundleName
    icon: images/smn-icon.png

  osx:
    <<: *AppleID
    icon: images/smn-keyboard-menu-icon.png
    version: 0.1.2
    resources: doc

  win:
    appName: *bundleName
    version: 0.2.0
    url: "http://divvun.no"
    uuid: "2c8b6556-16b7-4342-b0c0-57caffd536c6"
